version: '3.5'

services:

    tailscale:
        image: tailscale/tailscale:latest
        volumes:
            - "./tailscale/var_lib:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work 
        cap_add:                                    # Required for tailscale to work
            - net_admin
            - sys_module
        command: tailscaled
        ports:
            - "8880:80"
        environment:
            - TS_EXTRA_ARGS=--login-server=http://cloud.elec.ac.nz:8080
            - TS_HOSTNAME=proxy            # Will resolve to proxy.tart.telescopes.elec.ac.nz
            - TS_STATE_DIR=/var/lib/tailscale

        restart: unless-stopped
      

    ## Automatic Proxy which will resolve the VIRTUAL_HOST to the container specified.
    # Get an auth_key
    # 	docker compose -f proxy-compose.yml exec tailscale tailscale up --login-server http://cloud.elec.ac.nz:51820 --hostname=proxy --authkey ${AUTH_KEY}
    #
    # Only proxy hosts on the headscale network...
    nginx:
        image: nginx
        network_mode: "service:tailscale"
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/html:/var/www/html
            - ~/cache:/cache
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"
