services:
    telescope-proxy:
        build:
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - "8880:80"
        tmpfs:
            - /tmp
            - /run
            - /run/lock
        cap_add:                                    # Required for tailscale to work
            - net_admin
            - sys_module
        volumes:
             - ./nginx/nginx.conf:/etc/nginx/http.d/default.conf
             - ./nginx/html:/var/www/html
             - ~/cache:/cache
             - "./ts-proxy/state:/var/lib/tailscale"        # State data will be stored in this directory
             - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work 
        environment:
            - TS_ACCEPT_DNS=true
            - TS_EXTRA_ARGS=--login-server=https://cloud.elec.ac.nz
            - TS_HOSTNAME=telescope-proxy            # Will resolve to proxy.tart.telescopes.elec.ac.nz
            - TS_STATE_DIR=/var/lib/tailscale
