### This set of services is for the TART telescope. It orchestrates the following services:
#
#   RESTful API (api_container)
#   TART web front end app (web_app)
#   RESTful API documentation (api_doc_server). Connect to this via http://localhost:5000.
#   VPN connection to the cloud
#
#   Author: Tim Molteno (c) 2019-2024.

services:
    tailscale:
        image: tailscale/tailscale:latest
        ports:
            - "8000:80"
        volumes:
            - "./tailscale/var_lib:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
            - net_admin
            - sys_module
        environment:
            - TS_HOSTNAME=${TS_HOSTNAME}
            - TS_EXTRA_ARGS=--login-server=https://cloud.elec.ac.nz
            - TS_STATE_DIR=/var/lib/tailscale
        healthcheck:
            test: ["CMD", "tailscale", "status"] # Check if Tailscale is running
            interval: 1m # How often to perform the check
            timeout: 10s # Time to wait for the check to succeed
            retries: 3 # Number of retries before marking as unhealthy
            start_period: 10s # Time to wait before starting health checks
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
    api: # Port 5000
        image: tmolteno/tart_web_api
        volumes:
            -   data-volume:/telescope_data
            -   ~/tart_web_api_store:/app
            -   ~/telescope_config:/config_data
        # Comment the following two lines to disable access to the TART hardware (this allows testing of software on a desktop)
        devices:
           - /dev/spidev0.0
        environment:
            # Create a .env file with LOGIN_PW and SECRET_KEY next to the compose file.
            # Change the following to be something secure.
            # You will use this to login to your telescope from the web api.
            - LOGIN_PW=${LOGIN_PW}
            - SECRET_KEY=${SECRET_KEY}
        ports:
            - 5000:5000
        restart: always
        depends_on:
            - tailscale
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

    web_app: # Port 80 on service tailscale
        depends_on:
            - api
        volumes:
            - data-volume:/telescope_data
        environment:
            - NODE_ENV=production
        image: docker.io/tmolteno/tart_web_front_end:1.0.1
        network_mode: "service:tailscale"
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

volumes:
    # Mounted on each container as /telescope_data, used for raw data and vis data. This is a hardcoded path in each container.
    data-volume:
