### This set of services is for the TART telescope. It orchestrates the following services:
#
#   RESTful API (api_container)
#   TART web front end app (web_app)
#   RESTful API documentation (api_doc_server). Connect to this via http://localhost:5000.
#   VPN connection to AWS
#
#   Author: Tim Molteno (c) 2019-2024.

services:
    api: # Port 5000 internal only
        ports:
            - 5000:5000
        expose:
            - 5000
        build:
            context: ./containers/telescope_web_api
            dockerfile: Dockerfile.fastapi
        volumes:
            -   data-volume:/telescope_data
            -   ~/tart_web_api_store:/app/store
            -   ~/telescope_config:/config_data
        environment:
            # Change the following to be something secure. You will use this to login to your telescope from the web api.
            - LOGIN_PW=${LOGIN_PW}
            - SECRET_KEY=${SECRET_KEY}
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
    web_app:
        depends_on:
            - api
        volumes:
            - data-volume:/telescope_data
        environment:
            - NODE_ENV=production
        ports:
            - 80:80
        build:
            context: ./containers/web_app
            args:
                # Change this if you desire. Really only needed for running multiple TART telescopes and reverse proxying.
                tart_name: ${TS_HOSTNAME}
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

volumes:
    # Mounted on each container as /telescope_data, used for raw data and vis data. This is a hardcoded path in each container.
    data-volume:
