### This set of services is for the TART telescope. It orchestrates the following services:
#
#   RESTful API (api_container)
#   TART web front end app (web_app)
#   RESTful API documentation (api_doc_server). Connect to this via http://localhost:5000.
#   VPN connection to AWS
#
#   Author: Tim Molteno (c) 2019-2023.

services:

    api_container:
        build: 
            context: ./containers/telescope_web_api
        volumes:
            -   data-volume:/telescope_data
            -   ~/tart_web_api_store:/app
        # Comment the following two lines to disable access to the TART hardware (this allows testing of software on a desktop)
        environment:
            # Change the following to be something secure. You will use this to login to your telescope from the web api.
            - LOGIN_PW=passwd
        ports:
            - 5000:5000
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

    api_doc_server:
        build:
            context: ./containers/telescope_web_api
            dockerfile: Dockerfile.apidoc 
            args:
                tart_doc_url: tart.elec.ac.nz\/signal
        ports:
            - 8080:80
        restart: always

    web_app:
        depends_on:
            - api_container
            - api_doc_server
        volumes:
            - data-volume:/telescope_data
        environment:
            - NODE_ENV=production
        ports: 
            - 80:80
        build: 
            context: ./containers/web_app
            args:
                # Change this if you desire. Really only needed for running multiple TART telescopes and reverse proxying.
                tart_name: tart3dev
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

volumes:
    # Mounted on each container as /telescope_data, used for raw data and vis data. This is a hardcoded path in each container.
    data-volume:

