version: '2'

services:
    ## Now all these containers just need to be connected to the tailscale network

    ## Automatic Proxy which will resolve the VIRTUAL_HOST to the container specified.
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
        - "8880:80"
        environment:
        - DEFAULT_HOST=tart.api
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

    signal:
        image: jwilder/whoami
        expose:
        - "8000"
        environment:
        - VIRTUAL_HOST=tart.api
        - VIRTUAL_PORT=8000
        - VIRTUAL_PATH=/signal

    # curl -H "Host: tart.local" HTTP://localhost:8880/makhanda
    makhanda:
        image: jwilder/whoami
        expose:
        - "8000"
        environment:
        - VIRTUAL_HOST=tart.api
        - VIRTUAL_PORT=8000
        - VIRTUAL_PATH=/makhanda

