version: '3'

services:
    ## Now all these containers just need to be connected to the tailscale network

    # The config file is in config/config.yaml
    headscale:
        image: headscale/headscale:latest
        networks:
            reverseproxy-nw:
        volumes:
            - ./config:/etc/headscale/
            - ./data:/var/lib/headscale
        command: headscale serve
        ports:
            - "51820:8080"
            - "9090:9090"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9090"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
            start_interval: 5s
        restart: unless-stopped
        
    ## Automatic Proxy which will resolve the VIRTUAL_HOST to the container specified.
    nginx-proxy:
        image: jwilder/nginx-proxy
        depends_on:
            headscale:
                condition: service_healthy
        networks:
            reverseproxy-nw:
        ports:
            - "8880:80"
        environment:
            - DEFAULT_HOST=tart.api
            - TRUST_DOWNSTREAM_PROXY=true
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro


    # signal:
    #     image: jwilder/whoami
    #     expose:
    #     - "8000"
    #     environment:
    #     - VIRTUAL_HOST=tart.api
    #     - VIRTUAL_PORT=8000
    #     - VIRTUAL_PATH=/signal
    # 
    # # curl -H "Host: tart.local" HTTP://localhost:8880/makhanda
    # makhanda:
    #     image: jwilder/whoami
    #     expose:
    #     - "8000"
    #     environment:
    #     - VIRTUAL_HOST=tart.api
    #     - VIRTUAL_PORT=8000
    #     - VIRTUAL_PATH=/makhanda

# docker network create reverseproxy-nw
networks:
    reverseproxy-nw:
        external: true
