version: '3'

services:

    tailscale:
        image: tailscale/tailscale:latest
        networks:
            reverseproxy-nw:
        volumes:
            - "./tailscale/var_lib:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work 
        restart: unless-stopped
      
    # 1cd50ab45eb69c9c5cccba50f58fa14e7261e6e345d72cbd
    # tailscale up --login-server https://headscale.mydomain.com --authkey 3215a1ce7967c11e8ea844b3e199d3c46f9f5e7b660b48fb
    signal:
        image: jwilder/whoami
        expose:
            - "8000"
        networks:
            reverseproxy-nw:
        environment:
            - VIRTUAL_HOST=tart.api
            - VIRTUAL_PORT=8000
            - VIRTUAL_PATH=/signal
        
# docker network create reverseproxy-nw
networks:
    reverseproxy-nw:
        external: true
