services:
  telescope-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: tart-fastapi-dev
    ports:
      - "8000:5000"
    environment:
      - LOGIN_PW=password
      - SECRET_KEY=super-secret-123897219379179464asd13khk213
      - LOGLEVEL=DEBUG
    volumes:
      - ./tart_api:/app:rw # used for dev
      - ./hardware_interface:/hardware_interface:ro  # used for dev
      - ../../telescope_config.json:/config_data/telescope_config.json  # dummy telescope config used for dev
      - ../../calibrated_antenna_positions.json:/config_data/calibrated_antenna_positions.json # dummy antenna positions
      - telescope_data:/telescope_data
    restart: unless-stopped
    networks:
      - tart-network

  codegen:
    container_name: tart_codegen
    image: tart_codegen
    build:
      context: tart_codegen
      dockerfile: Dockerfile
    volumes:
      - ./schemas:/app/schemas:ro
      - ./tart_api/generated_models:/app/tart_api/generated_models:rw
    profiles:
      - codegen

  ui:
    image: ghcr.io/tart-telescope/web_app/viewer-root:main
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - telescope_data:/telescope_data:ro
    ports:
      - "8080:80"
    networks:
      - tart-network
    depends_on:
      - telescope-api

volumes:
  telescope_data:
    driver: local

networks:
  tart-network:
    driver: bridge
