
services:

    tailscale:
        image: tailscale/tailscale:latest
        ports:
            - "8000:80"
        volumes:
            - "./tailscale/var_lib:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work 
        cap_add:                                    # Required for tailscale to work
            - net_admin
            - sys_module
        env_file:
            - secrets.env                           # this file provides TS_AUTHKEY, TS_HOSTNAME 
        environment:
            - TS_EXTRA_ARGS=--login-server=https://cloud.elec.ac.nz
            - TS_STATE_DIR=/var/lib/tailscale

        restart: unless-stopped
      
    # Sidecar webserver to mimic a TART
    signal:
        image: nginx
        network_mode: "service:tailscale"
        depends_on:
            - tailscale
        restart: unless-stopped
