
services:

    # The headscale config file is in config/config.yaml
    headscale:
        image: headscale/headscale:v0.25
        # build:
        #     context: .
        #     network: host
        container_name: headscale
        volumes:
            - ./config:/etc/headscale/
            - ./hs_data/lib:/var/lib/headscale
            - ./hs_data/run:/var/run/headscale
        entrypoint: headscale serve
        ports:
            # - "8080:8080"
            - "9090:9090"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9090/metrics"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
            start_interval: 5s
        restart: unless-stopped

    # Caddy proxies both the headscale via cloud.elec.ac.nz, as well as the api.elec.ac.nz
    caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        security_opt:
            - label:disable
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
            
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./caddy_etc:/etc/caddy
            - /etc/localtime:/etc/localtime:ro

    headscale-ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        restart: unless-stopped
        container_name: headscale-ui
    #     # ports:
    #     #     - 9443:443

volumes:
  caddy_data:
    external: true
  caddy_config:
